CREATE TABLE Posts (
    "Id" BIGINT NOT NULL,
    "PostTypeId" INT,
    "AcceptedAnswerId" INT,
    "CreationDate" TIMESTAMP,
    "Score" INT,
    "ViewCount" INT,
    "Body" TEXT,
    "OwnerUserId" INT,
    "OwnerDisplayName" TEXT,
    "LastEditorUserId" INT,
    "LastEditorDisplayName" TEXT,
    "LastEditDate" TIMESTAMP,
    "LastActivityDate" TIMESTAMP,
    "Title" TEXT,
    "Tags" TEXT,
    "AnswerCount" INT,
    "CommentCount" INT,
    "FavoriteCount" INT,
    "ContentLicense" TEXT,
    "ParentId" INT,
    "CommunityOwnedDate" TIMESTAMP,
    "ClosedDate" TIMESTAMP
);

